spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fresh_delivery?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  sql:
    init:
      mode: never
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

logging:
  level:
    com.fresh: debug
    org.springframework: warn