spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fresh_delivery?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: prod_user
    password: prod_password

logging:
  level:
    com.fresh: info
    org.springframework: warn
  file:
    name: /var/log/fresh-delivery/app.log